version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Only create security updates
    open-pull-requests-limit: 0
    reviewers:
      - "@Sofie-Automation/maintainers"
  - package-ecosystem: "npm"
    directory: "/meteor"
    schedule:
      interval: "daily"
    # Only create security updates
    open-pull-requests-limit: 0
    reviewers:
      - "@Sofie-Automation/maintainers"
  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "daily"
    # Only create security updates
    open-pull-requests-limit: 0
    reviewers:
      - "@Sofie-Automation/maintainers"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@Sofie-Automation/operations"
